
/* Drop Tables */

DROP TABLE AUTH_INFO CASCADE CONSTRAINTS;
DROP TABLE COM_BOARD CASCADE CONSTRAINTS;
DROP TABLE LIKE_INFO CASCADE CONSTRAINTS;
DROP TABLE MEM_BOARD CASCADE CONSTRAINTS;
DROP TABLE PERSONAL CASCADE CONSTRAINTS;
DROP TABLE CUSTOM CASCADE CONSTRAINTS;
DROP TABLE AUTH CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_AUTH_AUTH_ID;
DROP SEQUENCE SEQ_AUTH_INFO_AUTH_INFO_ID;
DROP SEQUENCE SEQ_COM_BOARD_COM_NO;
DROP SEQUENCE SEQ_CUSTOM_CUS_PID;
DROP SEQUENCE SEQ_Like_info_LIKE_ID;
DROP SEQUENCE SEQ_MEM_BOARD_MB_NO;
DROP SEQUENCE SEQ_PERSONAL_PER_ID;




/* Create Sequences */

CREATE SEQUENCE SEQ_AUTH_AUTH_ID NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_AUTH_INFO_AUTH_INFO_ID NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_COM_BOARD_COM_NO NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CUSTOM_CUS_PID NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_Like_info_LIKE_ID NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MEM_BOARD_MB_NO NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PERSONAL_PER_ID NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;



/* Create Tables */

-- 권한 도메인 제약조건을 만드는 테이블
CREATE TABLE AUTH
(
	AUTH_ID number NOT NULL,
	AUTH_KIND nvarchar2(10) NOT NULL,
	PRIMARY KEY (AUTH_ID)
);


-- 권한 생성및 수정정보를 관리하기 위함
CREATE TABLE AUTH_INFO
(
	AUTH_INFO_ID number NOT NULL,
	-- 회원 키값
	CUS_PID number NOT NULL,
	AUTH_ID number NOT NULL,
	AUTH_INFO_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (AUTH_INFO_ID)
);


-- 댓글용 보드
CREATE TABLE COM_BOARD
(
	COM_NO number NOT NULL,
	MB_NO number NOT NULL,
	-- 회원 키값
	CUS_PID number NOT NULL,
	COM_CONTENT nvarchar2(50) NOT NULL,
	COM_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (COM_NO)
);


CREATE TABLE CUSTOM
(
	-- 회원 키값
	CUS_PID number NOT NULL,
	-- 회원이 기입한 아이디
	CUS_UID nvarchar2(30) NOT NULL,
	-- USER password
	CUS_PW nvarchar2(20) NOT NULL,
	-- user_ nickname
	CUS_NN nvarchar2(15) NOT NULL,
	-- user_gender
	CUS_GEN nvarchar2(10) NOT NULL,
	-- 학력
	CUS_GRADE nvarchar2(5) NOT NULL,
	CUS_COMMENT nvarchar2(600) NOT NULL,
	CUS_SIGNDATE date DEFAULT SYSDATE,
	AUTH_ID number NOT NULL,
	PRIMARY KEY (CUS_PID)
);


-- 좋아요 횟수를 Count 하기위한 Info
CREATE TABLE LIKE_INFO
(
	LIKE_ID number NOT NULL,
	MB_NO number NOT NULL,
	-- 회원 키값
	CUS_PID number NOT NULL,
	LIKE_CLICKDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (LIKE_ID)
);


CREATE TABLE MEM_BOARD
(
	MB_NO number NOT NULL,
	MB_TITLE nvarchar2(20) NOT NULL,
	-- 회원 키값
	CUS_PID number NOT NULL,
	MB_CONTENT nvarchar2(1500) NOT NULL,
	MB_POSTDATE date DEFAULT SYSDATE NOT NULL,
	MB_VIEWCOUNT number DEFAULT 0,
	MB_LIKE number DEFAULT 0 NOT NULL,
	MB_ATTACHFILE nvarchar2(50),
	MB_DOWNCOUNT number DEFAULT 0,
	PRIMARY KEY (MB_NO)
);


CREATE TABLE PERSONAL
(
	PER_ID number NOT NULL,
	PER_HAB nvarchar2(10) NOT NULL,
	-- 회원 키값
	CUS_PID number NOT NULL,
	PRIMARY KEY (PER_ID)
);



/* Create Foreign Keys */

ALTER TABLE AUTH_INFO
	ADD FOREIGN KEY (AUTH_ID)
	REFERENCES AUTH (AUTH_ID)
	ON DELETE CASCADE
;


ALTER TABLE CUSTOM
	ADD FOREIGN KEY (AUTH_ID)
	REFERENCES AUTH (AUTH_ID)
	ON DELETE CASCADE
;


ALTER TABLE AUTH_INFO
	ADD FOREIGN KEY (CUS_PID)
	REFERENCES CUSTOM (CUS_PID)
	ON DELETE CASCADE
;


ALTER TABLE COM_BOARD
	ADD FOREIGN KEY (CUS_PID)
	REFERENCES CUSTOM (CUS_PID)
	ON DELETE CASCADE
;


ALTER TABLE LIKE_INFO
	ADD FOREIGN KEY (CUS_PID)
	REFERENCES CUSTOM (CUS_PID)
	ON DELETE CASCADE
;


ALTER TABLE MEM_BOARD
	ADD FOREIGN KEY (CUS_PID)
	REFERENCES CUSTOM (CUS_PID)
	ON DELETE CASCADE
;


ALTER TABLE PERSONAL
	ADD FOREIGN KEY (CUS_PID)
	REFERENCES CUSTOM (CUS_PID)
	ON DELETE CASCADE
;


ALTER TABLE COM_BOARD
	ADD FOREIGN KEY (MB_NO)
	REFERENCES MEM_BOARD (MB_NO)
	ON DELETE CASCADE
;


ALTER TABLE LIKE_INFO
	ADD FOREIGN KEY (MB_NO)
	REFERENCES MEM_BOARD (MB_NO)
	ON DELETE CASCADE
;



